config/routes.rb
PortfolioManager::Application.routes.draw do
  resources :holdings

  match '/quotes/search', to: 'quotes#search', via: [:get, :post]

  resources :quotes

  resources :quote_histories

  devise_for :users

  root 'holdings#index'

  

end

app/models/quote.rb
require 'csv'

class Quote < ExternalModel

  attr_accessor :name, :symbol, :stock_exchange,
                :ask, :bid, :book_value_per_share, :previous_close,
                :day_low, :day_high, :year_high, :year_low,
                :error, :more_info, :notes

  def initialize(hash = {})
    Quote.attributes.each { |attribute|
      self.send("#{attribute}=", hash[attribute])
    }
  end

  def valid?
    self.error == 'N/A'
  end

  def self.find(symbols)

    response = Yahoo.quote_locator(symbols)

    results = []

    if response

      CSV.parse(response, :headers => Quote.attributes) do |row|
        results << Quote.new(row.to_hash)
      end
    end

    results
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show]

  # GET /quotes
  # GET /quotes.json
  def index
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    unless @quote.error == 'N/A'
      flash[:error] = @quote.error
      redirect_to quotes_path
    end
  end

  def search
    redirect_to quote_path params[:symbol]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params[:quote]
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_charts.html.haml
%ul.nav.nav-tabs.js-chart-nav
  %li.active
    %a{href: '#line_chart', data: {toggle: 'tab'}}
      Line
  %li
    %a{href: '#candlestick_chart', data: {toggle: 'tab'}}
      Candlestick
.tab-content
  .tab-pane.active{id: 'line_chart'}
    .progress.progress-striped.active
      .bar{style: 'width: 100%;'}
    .js-chart-error{style: 'display: none'}
      .alert.alert-error
        Chart could not be loaded.
    .js-chart.js-line-chart{style: 'height: 500px; min-width: 500px', data: {symbol: quote.symbol}}
  .tab-pane{id: 'candlestick_chart'}
    .progress.progress-striped.active{style: 'display: none'}
      .bar{style: 'width: 100%;'}
    .js-chart-error{style: 'display: none'}
      .alert.alert-error
        Chart could not be loaded.
    .js-chart.js-candlestick-chart{style: 'height: 500px; min-width: 500px', data: {symbol: quote.symbol}}

app/views/quotes/index.html.haml
.row
  .span4
    %h2 Search Quotes
    .well
      = form_tag quotes_search_path, method: 'get' do
        .controls
          = label_tag(:symbol, 'Enter symbol:')
          .control-group
            = text_field_tag(:symbol, nil, maxlength: 4)
          = submit_tag 'Search', class: 'btn btn-primary'

.row
  .span12
    = link_to 'Back', holdings_path, :class => 'btn'

app/views/quotes/show.html.haml
.row
  .span4
    %h2 Show Quote
    .well
      %p
        %strong Name:
        = @quote.name
      %p
        %strong Symbol:
        = @quote.symbol
      %p
        %strong Stock Exchange:
        = @quote.stock_exchange
      %p
        %strong Ask:
        = to_currency(@quote.ask)
      %p
        %strong Bid:
        = to_currency(@quote.bid)
      %p
        %strong Book Value per Share:
        = to_currency(@quote.book_value_per_share)
      %p
        %strong Previous Close:
        = to_currency(@quote.previous_close)
      %p
        %strong Day Low:
        = to_currency(@quote.day_low)
      %p
        %strong Day High:
        = to_currency(@quote.day_high)
      %p
        %strong Year Low:
        = to_currency(@quote.year_low)
      %p
        %strong Year High:
        = to_currency(@quote.year_high)

  .span8
    = render partial: 'quotes/charts', locals: {quote: @quote}
.row
  .span12
    = link_to 'Add Holding', new_holding_path(:holding => {:symbol => @quote.symbol}), :class => 'btn btn-primary'
    = link_to 'Back', holdings_path, :class => 'btn'