config/routes.rb
PortfolioManager::Application.routes.draw do
  resources :holdings

  match '/quotes/search', to: 'quotes#search', via: [:get, :post]

  resources :quotes

  resources :quote_histories

  devise_for :users

  root 'holdings#index'

  

end

app/models/holding.rb
class Holding < ActiveRecord::Base

  belongs_to :user

  validates :user_id, presence: true
  validates :symbol, presence: true, length: {in: 1..4}, format: {with: /[A-Z0-9]+/i,
                                                                  message: 'must be comprised of letters and numbers'}
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :quantity, presence: true, numericality: {greater_than: 0}

  def total_paid
    self.price * self.quantity
  end
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  before_action :set_holding, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /holdings
  # GET /holdings.json
  def index
    @holdings = current_user.holdings

    @presenter = Holdings::IndexPresenter.new(@holdings)

    @quotes_map = @presenter.quotes_map
  end

  # GET /holdings/1
  # GET /holdings/1.json
  def show
    @presenter = Holdings::ShowPresenter.new(@holding)

    @quote = @presenter.quote()

    flash.now[:error] = @quote.error unless @quote.error == 'N/A'
  end

  # GET /holdings/new
  def new
    @holding = current_user.holdings.new(params[:holding] ? holding_params : nil)
  end

  # GET /holdings/1/edit
  def edit
  end

  # POST /holdings
  # POST /holdings.json
  def create
    @holding = current_user.holdings.new(holding_params)

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding, notice: 'Holding was successfully created.' }
        format.json { render action: 'show', status: :created, location: @holding }
      else
        format.html { render action: 'new' }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holdings/1
  # PATCH/PUT /holdings/1.json
  def update
    respond_to do |format|
      if @holding.update(holding_params)
        format.html { redirect_to @holding, notice: 'Holding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1
  # DELETE /holdings/1.json
  def destroy
    @holding.destroy
    respond_to do |format|
      format.html { redirect_to holdings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holding
      @holding = Holding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holding_params
      params.require(:holding).permit(:symbol, :price, :quantity)
    end
end

app/helpers/holdings_helper.rb
module HoldingsHelper

  def purchase_value(holding)
    holding.quantity * holding.price
  end

  def computed_value(holding, quote)
    quote.previous_close == 'N/A' ? 'N/A' : (holding.quantity * quote.previous_close.to_f)
  end

  def change(holding, quote)
    computed = computed_value(holding, quote)
    computed == 'N/A' ? 'N/A' : computed - purchase_value(holding)
  end

  def percent_change(holding, quote)
    purchase = purchase_value(holding)
    change = change(holding, quote)
    if change == 'N/A'
      'N/A'
    else
      purchase == 0 ? 0 : (change / purchase) * 100
    end
  end

  def change_text_class(number)

    number = number.to_f

    if number > 0
      'text-success'
    elsif number < 0
      'text-error'
    else
      ''
    end
  end

  def change_icon_class(number)

    number = number.to_f

    if number > 0
      'icon-sort-up'
    elsif number < 0
      'icon-sort-down'
    else
      ''
    end
  end
end

app/views/holdings/_form.html.haml
= form_for @holding, :validate => true do |f|
  - if @holding.errors.any?
    #error_explanation
      %h2
        = pluralize(@holding.errors.count, 'error')
        prohibited this holding from being saved:
      %ul
        - @holding.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :symbol
    .controls
      = f.text_field :symbol
  .control-group
    = f.label :price
    .controls
      = f.text_field :price
  .control-group
    = f.label :quantity
    .controls
      = f.text_field :quantity
  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/holdings/edit.html.haml
%h1 Editing holding
= render 'form'
.row
  .span12
    = link_to 'Show', @holding, :class => 'btn'
    = #link_to 'Destroy', @holding, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'
    = link_to 'Back', holdings_path, :class => 'btn'

app/views/holdings/index.html.haml
%h1 Listing holdings
%table.table.table-striped.table-hover
  %thead
    %tr
      %th
        Symbol
      %th.hidden-phone
        Name
      %th.hidden-phone
        Price
      %th.hidden-phone
        Quantity
      %th.hidden-phone
        Purchase Value
      %th
        Computed Value
      %th
        Change
      %th
        \% Change
      %th.hidden-phone
      %th.hidden-phone
      %th.hidden-phone
  %tbody
    - @holdings.each do |holding|
      - quote = @quotes_map[holding.symbol]
      %tr
        %td
          = link_to holding.symbol, holding
        %td.hidden-phone
          = quote.name
        %td.hidden-phone
          = number_to_currency(holding.price)
        %td.hidden-phone
          = holding.quantity.round(2)
        %td.hidden-phone
          = number_to_currency(purchase_value(holding))
        %td
          = to_currency(computed_value(holding, quote))
        %td{:class => change_text_class(change(holding, quote))}
          = to_currency(change(holding, quote))
          %i{:class => change_icon_class(change(holding, quote))}
        %td{:class => change_text_class(percent_change(holding, quote))}
          = to_currency(percent_change(holding, quote))
          %i{:class => change_icon_class(percent_change(holding, quote))}
        %td.hidden-phone
          = link_to 'Show', holding, :class => 'btn btn-mini btn-primary'
        %td.hidden-phone
          = link_to 'Edit', edit_holding_path(holding), :class => 'btn btn-mini'
        %td.hidden-phone
          = link_to 'Destroy', holding, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger'
%br/
.row
  .span12
    = link_to 'New Holding', new_holding_path, :class => 'btn btn-primary'

app/views/holdings/new.html.haml
%h1 New holding
= render 'form'
.row
  .span12
    = link_to 'Back', holdings_path, :class => 'btn'

app/views/holdings/show.html.haml
.row
  .span4
    %h2 Show Holding
    .well
      %p
        %strong Name:
        = @quote.name
      %p
        %strong Symbol:
        = @holding.symbol
      %p
        %strong Price:
        = number_to_currency(@holding.price)
      %p
        %strong Quantity:
        = @holding.quantity
      %p
        %strong Purchase Value:
        = number_to_currency(purchase_value(@holding))
      %p
        %strong Computed Value:
        = to_currency(computed_value(@holding, @quote))
      %p
        %strong Change:
        %span{:class => change_text_class(change(@holding, @quote))}
          = to_currency(change(@holding, @quote))
          %i{:class => change_icon_class(change(@holding, @quote))}
      %p
        %strong % Change:
        %span{:class => change_text_class(percent_change(@holding, @quote))}
          = to_percentage(percent_change(@holding, @quote))
          %i{:class => change_icon_class(percent_change(@holding, @quote))}
  .span8
    = render partial: 'quotes/charts', locals: {quote: @quote}
.row
  .span12
    .page-controls
      = link_to 'Edit', edit_holding_path(@holding), :class => 'btn btn-primary'
      = link_to 'Destroy', @holding, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'
      = link_to 'Back', holdings_path, :class => 'btn'